version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: uber_postgres
    restart: always
    environment:
      POSTGRES_USER: uber_admin
      POSTGRES_PASSWORD: uber_pass
      POSTGRES_DB: uber_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: