"""create ride_status_history table

Revision ID: 5bc947c3fd52
Revises: 305da2eb5f8b
Create Date: 2026-07-08 20:40:19.857948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '5bc947c3fd52'
down_revision: Union[str, Sequence[str], None] = '305da2eb5f8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ride_status_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ride_id', sa.UUID(), nullable=False),
    sa.Column('status', postgresql.ENUM('REQUESTED', 'ACCEPTED', 'ONGOING', 'COMPLETED', 'CANCELLED', name='ridestatus', create_type=False), nullable=False),
    sa.Column('changed_by', sa.UUID(), nullable=False),
    sa.Column('changed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['ride_id'], ['rides.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ride_status_history')
    # ### end Alembic commands ###
