"""add driver and rider tables

Revision ID: 8e82e8ebacba
Revises: 129db96aa493
Create Date: 2026-07-03 21:07:43.519375

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e82e8ebacba'
down_revision: Union[str, Sequence[str], None] = '129db96aa493'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drivers',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('vehicle_make', sa.String(), nullable=False),
    sa.Column('vehicle_model', sa.String(), nullable=False),
    sa.Column('plate_number', sa.String(), nullable=False),
    sa.Column('license_number', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('OFFLINE', 'ONLINE', 'ON_TRIP', name='driverstatus'), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('license_number'),
    sa.UniqueConstraint('plate_number')
    )
    op.create_table('riders',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('payment_method_ref', sa.String(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('riders')
    op.drop_table('drivers')
    # ### end Alembic commands ###
